### ISSUE TITLE
Kill invoice system

### ISSUE THREAD

**Issue by by-cx** [by-cx/pcp#11]
Kill invoice system. Just log the activity and create API for 3rd party apps.

API:
- Statistics by day per app
- Statistics by day per user
- User identification
- App identification
- List of apps
- List of users
- History

This will be the biggest feature.

**Comment by yedpodtrzitko** [comment]
pozn.: pro vykreslovani html pouzivat opravdove sablony, nelepit dohromady stringy ve views

**Comment by by-cx** [comment]
Updated

**Comment by by-cx** [comment]
Done.
