### ISSUE TITLE
Wipe passwords

### ISSUE THREAD

**Issue by by-cx** [by-cx/pcp#3]
Wipe není dobře řešenej. Když ladím, tak nevidím, co server ve skutečnosti dělá. Nebylo by lepší odstranit jen heslo a zbytek tam nechat?

**Comment by yedpodtrzitko** [comment]
Samozrejme ze bylo, ale co jiny request to jine slozeni prikazu/parametru a vosefovat to vsechno nebylo v mych silach. Klidne mi tenhle issue prirad

**Comment by by-cx** [comment]
Máš ho mít :-) To heslo by mělo jít vysekat regexpem jak nic.

**Comment by by-cx** [comment]
Necháme být jak je. Bylo by to komplikovaný.
