### ISSUE TITLE
change DB password doesn't work as expected

### ISSUE THREAD

**Issue by yedpodtrzitko** [by-cx/pcp#33]
see this line: https://github.com/creckx/pcp/blob/master/wsgiadmin/db/views.py#L119

both parameters are DB name, one should be password!

(fixed in yedpodtrzitko/bootstrap branch, however this branch is not suitable for merge yet)

**Comment by by-cx** [comment]
Your code :-)

**Comment by yedpodtrzitko** [comment]
Great point, sir. However - it's in your app so I'm drawing attention to it, because if I remember correctly, you found this bug some time ago and now I stumbled upon it again

**Comment by by-cx** [comment]
Because you copied so many times :-)

**Comment by yedpodtrzitko** [comment]
fixed
