### ISSUE TITLE
Refresh ikona - rozhazuje formulář

### ISSUE THREAD

**Issue by by-cx** [by-cx/pcp#6]
U přidávání WSGI app rozhazuje refresh ikona formulář (posunuje pole ho do strany).

**Comment by yedpodtrzitko** [comment]
Ano, to povazuju za ficuru - kdyz jsou refreshe nad/pod, neni hned na prvni pohled patrne, ke kteremu elementu to patri. Nicmene lze to "opravit" smazanim tohoto pravidla v admin.css:
.ajax_refresh{ float: left;  }

**Comment by by-cx** [comment]
Chápu, vyřeším to nějak aby to vypadalo dobře

**Comment by by-cx** [comment]
Moved to v0.4
